services:
  backend:
    build: .
    working_dir: /code          
    command: python -m src.main
    volumes:
      - .:/code
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/code        
